export const superCodeObject = {
  products: [
    {
      brand: "SuperCode",
      category: "supercode",
      description:
        "The founders-glasses that bring Daniel to his destiny for creating his own E-Shop ",
      discountPercentage: 1,
      id: 1337,
      images: [
        "https://i.imgur.com/FvgoM9X.jpg",
        "https://i.imgur.com/FvgoM9X.jpg",
        "https://i.imgur.com/FvgoM9X.jpg",
        "https://i.imgur.com/FvgoM9X.jpg",
      ],
      price: 4999,
      rating: 5,
      stock: 1,
      thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
      title: "Daniels broken glasses",
    },
    {
      brand: "SuperCode",
      category: "supercode",
      description:
        "A evil duck that haunts Hector in his dream till he finally find him",
      discountPercentage: 99,
      id: 13372,
      images: [
        "https://i.imgur.com/VvxwIRX.jpeg",
        "https://i.imgur.com/VvxwIRX.jpeg",
        "https://i.imgur.com/VvxwIRX.jpeg",
        "https://i.imgur.com/VvxwIRX.jpeg",
      ],
      price: 299,
      rating: 1.0,
      stock: 1,
      thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
      title: "Hectors nightmare",
    },
    {
      brand: "SuperCode",
      category: "supercode",
      description: "Only the warm touch of a Tiger skin can make you happy",
      discountPercentage: 15,
      id: 13373,
      images: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3q6PT6OnwFsk_uIQVxCZxVCZgTBzWtBPgpg&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3q6PT6OnwFsk_uIQVxCZxVCZgTBzWtBPgpg&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3q6PT6OnwFsk_uIQVxCZxVCZgTBzWtBPgpg&usqp=CAU",
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3q6PT6OnwFsk_uIQVxCZxVCZgTBzWtBPgpg&usqp=CAU",
      ],
      price: 399,
      rating: 4.8,
      stock: 6,
      thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
      title: "Cyril`s second Skin",
    },
    {
      brand: "SuperCode",
      category: "supercode",
      description: "Stay hydrated,if you want code like Ingo",
      discountPercentage: 9.9,
      id: 13374,
      images: [
        "https://images.thalia.media/00/-/c5638ed563a84b10a148ac2ec08abbf0/dragon-ball-large-glass-400ml.jpeg",
        "https://images.thalia.media/00/-/c5638ed563a84b10a148ac2ec08abbf0/dragon-ball-large-glass-400ml.jpeg",
        "https://images.thalia.media/00/-/c5638ed563a84b10a148ac2ec08abbf0/dragon-ball-large-glass-400ml.jpeg",
        "https://images.thalia.media/00/-/c5638ed563a84b10a148ac2ec08abbf0/dragon-ball-large-glass-400ml.jpeg",
      ],
      price: 29,
      rating: 4.3,
      stock: 23,
      thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
      title: "Ingo`s Watercup",
    },
    {
      brand: "SuperCode",
      category: "supercode",
      description:
        "You want to become the best Animation-Designer in the World? That`s not possible but you can be the second best!",
      discountPercentage: 14.4,
      id: 13375,
      images: [
        "https://m.media-amazon.com/images/I/51YURPWZe4L._AC_UF1000,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/51YURPWZe4L._AC_UF1000,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/51YURPWZe4L._AC_UF1000,1000_QL80_.jpg",
        "https://m.media-amazon.com/images/I/51YURPWZe4L._AC_UF1000,1000_QL80_.jpg",
      ],
      price: 5,
      rating: 4.2,
      stock: 100,
      thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
      title: "Learn to Animate - with Matthias K",
    },
  ],
  total: 5,
}
