export const superCode = [
  {
    brand: "Fossil",
    category: "glasses",
    description: "Broken Glasses",
    discountPercentage: 14.4,
    id: 1337,
    images: [
      "https://i.dummyjson.com/data/products/92/1.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
    ],
    price: 2999,
    rating: 5.0,
    stock: 1,
    thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
    title: "Daniels broken glasses",
  },
  {
    brand: "Fossil",
    category: "glasses",
    description: "Broken Glasses",
    discountPercentage: 14.4,
    id: 13372,
    images: [
      "https://i.dummyjson.com/data/products/92/1.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
    ],
    price: 2999,
    rating: 5.0,
    stock: 1,
    thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
    title: "Daniels broken glasses",
  },
  {
    brand: "Fossil",
    category: "glasses",
    description: "Broken Glasses",
    discountPercentage: 14.4,
    id: 13373,
    images: [
      "https://i.dummyjson.com/data/products/92/1.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
    ],
    price: 2999,
    rating: 5.0,
    stock: 1,
    thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
    title: "Daniels broken glasses",
  },
  {
    brand: "Fossil",
    category: "glasses",
    description: "Broken Glasses",
    discountPercentage: 14.4,
    id: 1334,
    images: [
      "https://i.dummyjson.com/data/products/92/1.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
    ],
    price: 2999,
    rating: 5.0,
    stock: 1,
    thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
    title: "Daniels broken glasses",
  },
]
