export const superCode = [
  {
    brand: "Fossil",
    category: "glasses",
    description: "Broken Glasses",
    discountPercentage: 1,
    id: 1337,
    images: [
      "https://i.imgur.com/FvgoM9X.jpg",
      "https://i.imgur.com/FvgoM9X.jpg",
      "https://i.imgur.com/FvgoM9X.jpg",
      "https://i.imgur.com/FvgoM9X.jpg",
    ],
    price: 4999,
    rating: 5,
    stock: 1,
    thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
    title: "Daniels broken glasses",
  },
  {
    brand: "Hell",
    category: "Evil",
    description:
      "A evil duck that haunts Hector in his dream till he finally find him",
    discountPercentage: 99,
    id: 13372,
    images: [
      "https://i.imgur.com/VvxwIRX.jpeg",
      "https://i.imgur.com/VvxwIRX.jpeg",
      "https://i.imgur.com/VvxwIRX.jpeg",
      "https://i.imgur.com/VvxwIRX.jpeg",
    ],
    price: 299,
    rating: 1.0,
    stock: 1,
    thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
    title: "Hectors nightmare",
  },
  {
    brand: "filler",
    category: "filer",
    description: "filler",
    discountPercentage: 0,
    id: 13373,
    images: [
      "https://i.dummyjson.com/data/products/92/1.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
    ],
    price: 2999,
    rating: 5.0,
    stock: 1,
    thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
    title: "Daniels broken glassesl;sdfgj",
  },
  {
    brand: "Fossil",
    category: "glasses",
    description: "Broken Glasses2",
    discountPercentage: 14.4,
    id: 13374,
    images: [
      "https://i.dummyjson.com/data/products/92/1.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
    ],
    price: 2999,
    rating: 5.0,
    stock: 1,
    thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
    title: "Daniels broken glasses2",
  },
]

export const superCodeObject = {
  products: [
    {
      brand: "Fossil",
      category: "glasses",
      description: "Broken Glasses",
      discountPercentage: 1,
      id: 1337,
      images: [
        "https://i.imgur.com/FvgoM9X.jpg",
        "https://i.imgur.com/FvgoM9X.jpg",
        "https://i.imgur.com/FvgoM9X.jpg",
        "https://i.imgur.com/FvgoM9X.jpg",
      ],
      price: 4999,
      rating: 5,
      stock: 1,
      thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
      title: "Daniels broken glasses",
    },
    {
      brand: "Hell",
      category: "Evil",
      description:
        "A evil duck that haunts Hector in his dream till he finally find him",
      discountPercentage: 99,
      id: 13372,
      images: [
        "https://i.imgur.com/VvxwIRX.jpeg",
        "https://i.imgur.com/VvxwIRX.jpeg",
        "https://i.imgur.com/VvxwIRX.jpeg",
        "https://i.imgur.com/VvxwIRX.jpeg",
      ],
      price: 299,
      rating: 1.0,
      stock: 1,
      thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
      title: "Hectors nightmare",
    },
    {
      brand: "filler",
      category: "filer",
      description: "filler",
      discountPercentage: 0,
      id: 13373,
      images: [
        "https://i.dummyjson.com/data/products/92/1.jpg",
        "https://i.dummyjson.com/data/products/92/2.jpg",
        "https://i.dummyjson.com/data/products/92/2.jpg",
        "https://i.dummyjson.com/data/products/92/2.jpg",
      ],
      price: 2999,
      rating: 5.0,
      stock: 1,
      thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
      title: "Daniels broken glassesl;sdfgj",
    },
    {
      brand: "Fossil",
      category: "glasses",
      description: "Broken Glasses2",
      discountPercentage: 14.4,
      id: 13374,
      images: [
        "https://i.dummyjson.com/data/products/92/1.jpg",
        "https://i.dummyjson.com/data/products/92/2.jpg",
        "https://i.dummyjson.com/data/products/92/2.jpg",
        "https://i.dummyjson.com/data/products/92/2.jpg",
      ],
      price: 2999,
      rating: 5.0,
      stock: 1,
      thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
      title: "Daniels broken glasses2",
    },
  ],
  total: 4,
}
